# Generated by Django 5.1 on 2025-01-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_learn_greek', '0003_alter_user_managers_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
