# Generated by Django 5.1 on 2024-12-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_noun', models.CharField(max_length=100)),
                ('nominative_singular', models.CharField(max_length=100)),
                ('genitive_singular', models.CharField(max_length=100)),
                ('accusative_singular', models.CharField(max_length=100)),
                ('vocative_singular', models.CharField(max_length=100)),
                ('nominative_plural', models.CharField(max_length=100)),
                ('genitive_plural', models.CharField(max_length=100)),
                ('accusative_plural', models.CharField(max_length=100)),
                ('vocative_plural', models.CharField(max_length=100)),
            ],
        ),
    ]
