# Generated by Django 5.1 on 2024-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='gender',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
