# Generated by Django 5.1 on 2024-11-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb_type', models.CharField(max_length=10)),
                ('present_first_singular', models.CharField(max_length=100)),
                ('present_second_singular', models.CharField(max_length=100)),
                ('present_third_singular', models.CharField(max_length=100)),
                ('present_first_plural', models.CharField(max_length=100)),
                ('present_second_plural', models.CharField(max_length=100)),
                ('present_third_pluran', models.CharField(max_length=100)),
                ('aorist_first_singular', models.CharField(max_length=100)),
                ('aorist_second_singular', models.CharField(max_length=100)),
                ('aorist_third_singular', models.CharField(max_length=100)),
                ('aorist_first_plural', models.CharField(max_length=100)),
                ('aorist_second_plural', models.CharField(max_length=100)),
                ('aorist_third_plural', models.CharField(max_length=100)),
                ('imperfect_first_singular', models.CharField(max_length=100)),
                ('imperfect_second_singular', models.CharField(max_length=100)),
                ('imperfect_third_singular', models.CharField(max_length=100)),
                ('imperfect_first_plural', models.CharField(max_length=100)),
                ('imperfect_second_plural', models.CharField(max_length=100)),
                ('imperfect_third_plural', models.CharField(max_length=100)),
                ('perfect_first_singular', models.CharField(max_length=100)),
                ('perfect_second_singular', models.CharField(max_length=100)),
                ('perfect_third_singular', models.CharField(max_length=100)),
                ('perfect_first_plural', models.CharField(max_length=100)),
                ('perfect_second_plural', models.CharField(max_length=100)),
                ('perfect_third_plural', models.CharField(max_length=100)),
                ('plusperfect_first_singular', models.CharField(max_length=100)),
                ('plusperfect_second_singular', models.CharField(max_length=100)),
                ('plusperfect_third_singular', models.CharField(max_length=100)),
                ('plusperfect_first_plural', models.CharField(max_length=100)),
                ('plusperfect_second_plural', models.CharField(max_length=100)),
                ('plusperfect_third_plural', models.CharField(max_length=100)),
                ('future_first_singular', models.CharField(max_length=100)),
                ('future_second_singular', models.CharField(max_length=100)),
                ('future_third_singular', models.CharField(max_length=100)),
                ('future_first_plural', models.CharField(max_length=100)),
                ('future_second_plural', models.CharField(max_length=100)),
                ('future_third_plural', models.CharField(max_length=100)),
            ],
        ),
    ]
