# Generated by Django 5.1 on 2024-11-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='infinitive',
            field=models.CharField(default='placeholder', max_length=100, unique=True),
        ),
    ]
