# Generated by Django 5.1 on 2024-12-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugator', '0002_verb_infinitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='infinitive',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
