# Generated by Django 5.1.5 on 2025-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransparentWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', help_text="Language code (e.g., 'en', 'fr', 'de')", max_length=100)),
                ('greek_word', models.CharField(max_length=100)),
                ('language_word', models.CharField(blank=True, default='', max_length=100)),
                ('pronunciation', models.CharField(blank=True, default='', max_length=100)),
                ('etymology', models.TextField(blank=True)),
                ('example_greek', models.TextField(blank=True)),
                ('example_translation', models.TextField(blank=True)),
                ('category', models.CharField(default='other', max_length=100)),
            ],
            options={
                'unique_together': {('language', 'greek_word')},
            },
        ),
    ]
