# Generated by Django 5.1 on 2024-11-19 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greek_word', models.CharField(help_text='Enter the word in Greek (only Greek Alphabet allowed)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='The Greek word must contain only Greek alphabet characters.', regex='^[Α-Ωα-ωΆ-Ώά-ώ]+$')])),
                ('pronounciation', models.CharField(help_text='Enter the pronounciation (literally in latin script)', max_length=30)),
                ('translation', models.CharField(help_text='Enter the translation(s) in the desired language(s)', max_length=30)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
