# Generated by Django 5.1 on 2024-12-07 19:22

import dictionary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='greek_word',
            field=models.CharField(help_text='Enter the word in Greek (only Greek Alphabet allowed, optionally with an article).', max_length=30, unique=True, validators=[dictionary.validators.validate_greek]),
        ),
    ]
