# Generated by Django 5.1 on 2024-12-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_dictionary_greek_word'),
        ('we_learn_greek', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='we_learn_greek.user'),
        ),
    ]
